---
# tasks file for Dell-Networking.dellos-vrf

 - name: "Generating VRF configuration for dellos9"
   template:
      src: dellos9_vrf.j2
      dest: "{{ build_dir }}/vrf9_{{hostname}}.conf.part"
   when: (ansible_network_os == "dellos9" or ansible_net_os_name == "dellos9") and ((dellos_cfg_generate | default('False')) | bool)
#   notify: save config os9
   register: generate_output

 - name: "Provisioning VRF configuration for dellos9"
   dellos9_config:
      src: dellos9_vrf.j2
   when: (ansible_network_os == "dellos9" or ansible_net_os_name == "dellos9")
#   notify: save config os9
   register: output


